# Generated by Django 2.1 on 2019-01-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('poll_interval', models.IntegerField(verbose_name='poll interval in seconds')),
                ('status', models.IntegerField(choices=[(0, 'unknown'), (2, 'online'), (1, 'offline')], default=0)),
                ('status_time', models.DateTimeField(auto_now_add=True)),
                ('last_poll', models.DateTimeField(blank=True, null=True)),
                ('next_poll', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
